# PostgreSQL Database Connection
# We assume a local Postgres instance running on standard port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_triage
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
# We use 'validate' because Flyway will create our tables via SQL scripts. 
# Spring JPA will just check that our Java code matches the database schema.
spring.jpa.hibernate.ddl-auto=validate
# Print SQL to the console so we can see what Spring is doing behind the scenes
spring.jpa.show-sql=true
