# PostgreSQL Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticket_triage}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
# We use 'validate' because Flyway will create our tables via SQL scripts. 
# Spring JPA will just check that our Java code matches the database schema.
spring.jpa.hibernate.ddl-auto=validate
# Print SQL to the console so we can see what Spring is doing behind the scenes
spring.jpa.show-sql=true
